---
- name: Update apt
  apt: update_cache=yes cache_valid_time=86400

- name: Install MongoDB
  action: apt pkg={{ item }} state=installed
  with_items:
   - mongodb-server

- name: Ensure MongoDB service running
  service: name=mongodb state=started
