- name: Create swap file
  command: fallocate -l {{ swap_file_size }} {{ swap_file_path }}
           creates="{{ swap_file_path }}"

- name: Change swap file permissions
  file: path="{{ swap_file_path }}" owner=root group=root mode=0600

- name: Format swap file
  command: mkswap {{ swap_file_path }}

- name: Write swap entry in fstab
  mount: name=none
         src={{ swap_file_path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present

- name: Mount swap
  command: swapon {{ swap_file_path }}
